### ISSUE TITLE
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

### ISSUE THREAD

**Issue by Vonity** [lxxue/FRNN#14]
Hi,
There is a problem in the FRNN installing. Could you give me some advice for this problem? Thank you

'''
cd ../../
pip install -e .

D:\Anaconda\envs\SPT\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
 warnings.warn(f'Error checking compiler version for {compiler}: {error}')
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
'''

My environment is as follows:
Python 3.8
CUDA 11.8
Pytorch 2.0.1

**Comment by lxxue** [comment]
Hi,

I am not familiar with the build environment on Windows. I did some quick search and this [post](https://blog.51cto.com/SpaceVision/3086958) about encoding might be useful for your case.

**Comment by Vonity** [comment]
Thank you for your help. I have solved this problem. Just change all the long type to long long type.

**Comment by lxxue** [comment]
Did you clone an old version of FRNN? I thought in this PR #13 all the `long` types had been changed to `int64_t` for compatibility. Is there a missing one?

**Comment by Vonity** [comment]
Yeah, I cloned the old one and I just found out now.
