### ISSUE TITLE
RuntimeError: Unknown layout

### ISSUE THREAD

**Issue by 1163710216** [lxxue/FRNN#20]
File "/media/willam/colorfuldisk/superpoint_transformer/src/dependencies/FRNN/frnn/frnn.py", line 174, in forward
    idxs, dists = _C.find_nbrs_cuda(sorted_points1, sorted_points2,
                                        lengths1, lengths2, pc2_grid_off,
                                        sorted_points1_idxs,
                                        sorted_points2_idxs, grid_params_cuda,
                                        K, r, r * r)
RuntimeError: Unknown layout

I checked all the parameters are tensor. layout is torch.strided. i don't know where is the problem.

**Comment by lxxue** [comment]
Hi, I guess the layout for input points needed to be contiguous. Can you do `tensor.contiguous()` for the input tensor for the `frnn.frnn_grid_points`?

**Comment by 1163710216** [comment]
I executed the code below you give to me,and I got the same error "Unknown layout".


import torch
from src.dependencies.FRNN import frnn
points1 = torch.load("src/dependencies/FRNN/tests/pts.pth")
points2 = torch.load("src/dependencies/FRNN/tests/pts.pth")
points1 = points1[None, ...]
points2 = points2[None, ...]
points1 = points1.float().cuda()
points2 = points2.float().cuda()
K = 5
r = 0.1
dists, idxs, nn, grid = frnn.frnn_grid_points(
        points1, points2, None, None, K, r, grid=None, return_nn=False, return_sorted=True)

print(dists, idxs, nn, grid)


error message:


Traceback (most recent call last):
  File "/media/willam/colorfuldisk/superpoint_transformer/mytest_frnn.py", line 12, in <module>
    dists, idxs, nn, grid = frnn.frnn_grid_points(
  File "/media/willam/colorfuldisk/superpoint_transformer/src/dependencies/FRNN/frnn/frnn.py", line 333, in frnn_grid_points
    idxs, dists, sorted_points2, pc2_grid_off, sorted_points2_idxs, grid_params_cuda = _frnn_grid_points.apply(
  File "/home/willam/miniconda3/envs/panoseg/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/media/willam/colorfuldisk/superpoint_transformer/src/dependencies/FRNN/frnn/frnn.py", line 176, in forward
    idxs, dists = _C.find_nbrs_cuda(sorted_points1, sorted_points2,
RuntimeError: Unknown layout

**Comment by lxxue** [comment]
Can you provide more information about your environment like pytorch/cuda version? 

I just installed pytorch 2.3.0 with cuda 11.8 and it works fine for me.

**Comment by 1163710216** [comment]
pytorch 2.2.0
cuda 11.8
gcc 7.5

**Comment by lxxue** [comment]
I think this is an issue specific to this pytorch version: https://github.com/pytorch/pytorch/issues/120020. You can switch to another version and retry the whole pipeline.

**Comment by 1163710216** [comment]
I failed to compile FRNN with gcc 12  and successed with gcc 7.5

**Comment by 1163710216** [comment]
does gcc version mattes?

**Comment by 1163710216** [comment]
the code got error when executed

 idxs, dists = _C.find_nbrs_cuda(sorted_points1, sorted_points2,
                                        lengths1, lengths2, pc2_grid_off,
                                        sorted_points1_idxs,
                                        sorted_points2_idxs, grid_params_cuda,
                                        K, r, r * r)

which was compiled from

find_nbrs.cu:
std::tuple<at::Tensor, at::Tensor> FindNbrsCUDA(
    const at::Tensor points1, const at::Tensor points2,
    const at::Tensor lengths1, const at::Tensor lengths2,
    const at::Tensor pc2_grid_off, const at::Tensor sorted_points1_idxs,
    const at::Tensor sorted_points2_idxs, const at::Tensor params, int K,
    const at::Tensor rs, const at::Tensor r2s)

**Comment by lxxue** [comment]
I am using gcc 10.5.0. Can you recompile FRNN with pytorch 2.3.0 or 2.1.0 and check the result?

**Comment by 1163710216** [comment]
pytorch 2.3.0 cuda 11.8 gcc-10 can work.
