### ISSUE TITLE
_C Import Error, undefined symbol

### ISSUE THREAD

**Issue by dapterzidis** [lxxue/FRNN#21]
**Ubuntu 22.04, Torch 2.3+cu121, Cuda 12.1**
After the completion of the installation that completed properly when I try to run a script importing FRNN, I receive the following error. I assume that it may have to do with cuda, and torch versions (?) given that my system versions are way to distant from the original ones. In any case any recommendation that doesn't force me to downgrade all APIs would be helpful. 

`File "/*/*/*/*/*/*.py", line 5, in <module> 
import frnn
File "/*/*/*/*/FRNN/frnn/__init__.py", line 2, in <module>
    from .frnn import frnn_grid_points, frnn_gather, frnn_bf_points, _C
  File "/*/*/*/*/FRNN/frnn/frnn.py", line 7, in <module>
    from frnn import _C
ImportError: /*/*/*/*/FRNN/frnn/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPKvmm
`

Especially this is, I believe the informative part.

**ImportError: /*/*/*/*/FRNN/frnn/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPKvmm**

Thank you in advance for your time

**Comment by lxxue** [comment]
Hi, I just built an environment with `torch2.3.1+cu121` on Ubuntu 22.04. It works for me. 

I met such `undefined symbol` error in other repos before. In that case, it came from cuda version mismatch between build time and run time. Maybe you can check the build environment and rebuild the library again?

**Comment by dapterzidis** [comment]
Hello, 
I just run ldd on the binary and for some reason the environment path did not have the path to torch implemented. I did that and it worked. Sorry to bother you with this and thank you for your time and consideration.
