### ISSUE TITLE
Cannot import name "_C" 

### ISSUE THREAD

**Issue by samira-jpg** [lxxue/FRNN#23]
Hello, 
Thank you for your work on this library. I'm currently coming across the issue after cloning and installing the lirary and running any import FRNN command, i get The following error: 
`5 import torch
----> 6 from frnn import _C  # Import within the function to avoid circular import
      7 from torch.autograd import Function
      8 from torch.autograd.function import once_differentiable

ImportError: cannot import name '_C' from partially initialized module 'frnn' (most likely due to a circular import) (/content/superpoint_transformer/src/dependencies/FRNN/frnn/frnn.py)`

There was a closed issue with this error but the solution options there didn't work for me, I'm currently running on Google Colab so I also tried restarting the runtimes.
Could you assist with how I could possibly resolve this? Thank you!

**Comment by lxxue** [comment]
Hi, could you share the colab notebook with me so I can try it out myself?

**Comment by samira-jpg** [comment]
> Hi, could you share the colab notebook with me so I can try it out myself?

Sure, shall I share it with the email listed under the Github account?

**Comment by lxxue** [comment]
> > Hi, could you share the colab notebook with me so I can try it out myself?
> 
> Sure, shall I share it with the email listed under the Github account?

Yes. I do not have time for this right now, but I will work on it later this week.
