### ISSUE TITLE
What are the limits on dimension and K?

### ISSUE THREAD

**Issue by yuhao** [lxxue/FRNN#3]
According to `DispatchKernel1D` (line 119) in `frnn/csrc/utils/dispatch.h`, in V1 K should be within 2 and 8, but when I pass D=16 and K=5, I still get an error saying that K should be in this range [2, 8].

Also, `frnn/frnn.py` says that `"for now only point clouds of dimension 2-16 is supported"`, but in `frnn/csrc/grid/grid.h` seems like to trigger V2 D should be between 1 and 8 and K should be between 1 and 32. So which one is correct?

I guess I can dig into the code a bit to figure out the exact limits on D and K, but would you mind telling me, for now, what the supported D and K ranges are?

**Comment by lxxue** [comment]
Sorry I just added the support for large K and D without testing it thoroughly. V1 should support D up to 32 and arbitrary K. I follow the practice here:

https://github.com/facebookresearch/pytorch3d/blob/f593bfd3c258b0ff2b7bdbabfb06ab5210b43a52/pytorch3d/csrc/knn/knn.cu#L264-L275

Will fix these conflicts now, thanks!

**Comment by lxxue** [comment]
Do you need to work with very large D or very large K?

**Comment by yuhao** [comment]
Hi Lixin,

Both, although a large D (> 1000) is more important.

Thanks for taking a look at this. I had a couple of questions:
* What's the difference between V1 and V2? Seems like they are optimized
for different D and K ranges?
* This is more of a PyTorch question, but does PyTorch fall back to a CPU
implementation when D and K are out of the supported ranges?

Thanks.

Yuhao

**Comment by lxxue** [comment]
Hi Yuhao,

For the first question, the difference is here: in V1 we access the GPU global memory directly
https://github.com/lxxue/FRNN/blob/fd3245731caacd0bc336ff9da89701669b629a49/frnn/csrc/grid/find_nbrs.cu#L295
while in V2 we use local memory to store it first and store it to the global memory in the end
https://github.com/lxxue/FRNN/blob/fd3245731caacd0bc336ff9da89701669b629a49/frnn/csrc/grid/find_nbrs.cu#L341-L342
https://github.com/lxxue/FRNN/blob/fd3245731caacd0bc336ff9da89701669b629a49/frnn/csrc/grid/find_nbrs.cu#L383
https://github.com/lxxue/FRNN/blob/fd3245731caacd0bc336ff9da89701669b629a49/frnn/csrc/grid/find_nbrs.cu#L412-L415

For the second question, I didn't support this in FRNN now, and my CPU implementation is deprecated long ago which only serves as ground truth for my GPU implementation. I could implement a V0 version like this https://github.com/facebookresearch/pytorch3d/blob/f593bfd3c258b0ff2b7bdbabfb06ab5210b43a52/pytorch3d/csrc/knn/knn.cu#L28 for any D and K, where the point of D dimension is not cached locally. However, I doubt my implementation would be efficient as I only construct a 3D grid for any D-dim data. If most of the points locate in a 3D subspace a PCA would be helpful.

I can add the support for large D now, and then you can compare it with pytorch3d's KNN to see if FRNN really helps.

Best,
Lixin

**Comment by lxxue** [comment]
Could you give me an upper bound for D since I use template recursion to compile for all D?

I had some trouble compiling it with a large D due to the recursion depth...

**Comment by yuhao** [comment]
I am doing on my radius search implementation and want to benchmark against existing approach. My implementation supports arbitrary D (as long as memory allows) so ideally it would be great if you could support arbitrary D. Yours is the fastest CUDA implementation I can find that's why I am asking ;)

Also, am I correct that vanilla KNN in pytorch always uses a brute force search whereas you build the grid, but supports only smaller Ds and Ks?

What's preventing your implementation to support a large D?

**Comment by lxxue** [comment]
Yes, my initial version only supports 3D and small K. Now I extend it to large Ds and large Ks while still using a 3D grid, so I guess it won't be too effective for very large D. I can add an optional PCA in the code for now. But using a user configurable M-dim grid would take more efforts.
For very large D I initially had the problem of compiling it due to deep template recursion. Now I found the flag for set the limit for it so it wont be a problem though I still need to specify a very large D beforehand for the compilation

**Comment by yuhao** [comment]
Thanks.

I saw that with K larger than 32 we will fall back to V1 too. I am assuming
that if I am on a GPU with large device memory I should be able to increase
the threshold of K?

Also, the `_C.insert_points_cuda` time on points2 is significantly faster
than that of points1. I could look at the code, but is there an intuitive
explanation to this?

Finally, what point ordering is used here when reordering points2 and
points2? Is it traversal and x, y, and z dimensions, or something
fancier like the z-order?

Yuhao

**Comment by lxxue** [comment]
I think the max value for K is more related to the size of the register file rather than the size of the global memory. As K increase, the register cannot hold all the value and will place it onto local memory, which is as slow as global memory. You can check this [link](https://www.microway.com/hpc-tech-tips/gpu-memory-types-performance-comparison/) for further information about GPU memory types. I am not a CUDA expert, so it is better to take my judgements with a grain of salt.

For the second question, I believe the difference is in the grid. The grid is the bounding box of the `points2` which can be quite far away from `points1`. In the extreme case where all points in `points1` assigned to the same cell of the grid, it could be slow due to some read-after-write dependencies & bank conflicts. Maybe you can try to use the same `points1` and `points2` to see if my conjecture is correct or not.

The ordering of points is mainly based on the cell index (points in cell (0, 0, 2) will be placed after points in cell (0, 0, 1)). For points in the same cell, the ordering is based on the insertion order of that point in the cell (e.g. the 2nd point inserted into the cell will be placed after the 1st point inserted into the cell).

Best,
Lixin

**Comment by yuhao** [comment]
> I think the max value for K is more related to the size of the register file rather than the size of the global memory. As K increase, the register cannot hold all the value and will place it onto local memory, which is as slow as global memory. You can check this [link](https://www.microway.com/hpc-tech-tips/gpu-memory-types-performance-comparison/) for further information about GPU memory types. I am not a CUDA expert, so it is better to take my judgements with a grain of salt.

Oh I see. So the values holding that you ideally want to hold in the registers are the top-K array, right? And in the end you copy the top-K array to the global memory? 
https://github.com/lxxue/FRNN/blob/fd3245731caacd0bc336ff9da89701669b629a49/frnn/csrc/grid/find_nbrs.cu#L383
and
https://github.com/lxxue/FRNN/blob/fd3245731caacd0bc336ff9da89701669b629a49/frnn/csrc/grid/find_nbrs.cu#L412-L415

> For the second question, I believe the difference is in the grid. The grid is the bounding box of the `points2` which can be quite far away from `points1`. In the extreme case where all points in `points1` assigned to the same cell of the grid, it could be slow due to some read-after-write dependencies & bank conflicts. Maybe you can try to use the same `points1` and `points2` to see if my conjecture is correct or not.

I am indeed using the same points1 and points2. So the bounding box is exactly the same, and I still see very fast insertion on points2.
 
> The ordering of points is mainly based on the cell index (points in cell (0, 0, 2) will be placed after points in cell (0, 0, 1)). For points in the same cell, the ordering is based on the insertion order of that point in the cell (e.g. the 2nd point inserted into the cell will be placed after the 1st point inserted into the cell).

I see. I thought it was a z-order, because I thought the code is based on the idea from https://github.com/InteractiveComputerGraphics/cuNSearch, which computes a z-order.

also, seems like in your implementation once you calculate the new points order you actually reorder the points in the device memory, whereas the cuNsearch doesn't do the actual memory layout reordering; it just calculates the reordered indices.

**Comment by lxxue** [comment]
> Oh I see. So the values holding that you ideally want to hold in the registers are the top-K array, right? And in the end you copy the top-K array to the global memory?
Yes, exactly.

> I am indeed using the same points1 and points2. So the bounding box is exactly the same, and I still see very fast insertion on points2.
I might need to take a closer look at the code and see what could be the reason.

> I see. I thought it was a z-order, because I thought the code is based on the idea from https://github.com/InteractiveComputerGraphics/cuNSearch, which computes a z-order.
You can check this [slide](https://github.com/lxxue/FRNN/blob/master/frnn_pre.pdf) for the visualization of the order and the algorithm. The code is based on the algorithm proposed [here](https://on-demand.gputechconf.com/gtc/2014/presentations/S4117-fast-fixed-radius-nearest-neighbor-gpu.pdf).

> also, seems like in your implementation once you calculate the new points order you actually reorder the points in the device memory, whereas the cuNsearch doesn't do the actual memory layout reordering; it just calculates the reordered indices.
Yes, I create a copy of the two point clouds and actually sort them so that in the search stage, memory locality can be utilized. And this is crucial for the performance as shown in the slide mentioned above.

**Comment by yuhao** [comment]
> You can check this [slide](https://github.com/lxxue/FRNN/blob/master/frnn_pre.pdf) for the visualization of the order and the algorithm. The code is based on the algorithm proposed [here](https://on-demand.gputechconf.com/gtc/2014/presentations/S4117-fast-fixed-radius-nearest-neighbor-gpu.pdf).

If I am not mistaken, this presentation is also mentioned on the cuNSearch page (https://github.com/InteractiveComputerGraphics/cuNSearch), and that's why I thought these two are the same. Now, in cuNSearch, the calculate the z-order curve (https://github.com/InteractiveComputerGraphics/cuNSearch/blob/master/src/cuNSearchKernels.cu#L102), but yours seems to be different?

> Yes, I create a copy of the `points1` and `points2` and actually sort them so that in the search stage, memory locality can be utilized. And this is crucial for the performance as shown in the slide mentioned above.

That's what I thought, but the cuNSearch code, which is what that GTC presentation is based on, doesn't do the actual reordering.

**Comment by lxxue** [comment]
> If I am not mistaken, this presentation is also mentioned on the cuNSearch page (https://github.com/InteractiveComputerGraphics/cuNSearch), and that's why I thought these two are the same. Now, in cuNSearch, the calculate the z-order curve (https://github.com/InteractiveComputerGraphics/cuNSearch/blob/master/src/cuNSearchKernels.cu#L102), but yours seems to be different?

Aha I didn't see the reference there. I guess the so-called z-order is exactly what I said previously according to the code here:
https://github.com/InteractiveComputerGraphics/cuNSearch/blob/b3b708de5a396826aecc74b47b390418f92c8dcb/src/cuNSearchKernels.cu#L119-L121

> That's what I thought, but the cuNSearch code, which is what that GTC presentation is based on, doesn't do the actual reordering.

I think this is the [code](https://github.com/NVIDIA/gvdb-voxels/blob/6f438f808ba9334acf2ee1122ca224c0988e7d25/source/gFluidSurface/fluid_system_cuda.cu#L247) from the author of the GTC presentation, though I don't want to check this huge codebase to see if they sort the particles or not... I believe the author also sorts the particles (see slide \#10 of the GTC pre). And the author of cuNSearch said this:
>  The reordering will improve the performance of future neighborhood queries and accesses.

**Comment by yuhao** [comment]
> Aha I didn't see the reference there. I guess the so-called z-order is exactly what I said previously according to the code here:
> https://github.com/InteractiveComputerGraphics/cuNSearch/blob/b3b708de5a396826aecc74b47b390418f92c8dcb/src/cuNSearchKernels.cu#L119-L121

I don't quite think so. I think the way they generate the order across cells is different. You are expanding on x, y, and z dimensions right? They generate the Morton code: https://en.wikipedia.org/wiki/Z-order_curve. Am I misunderstanding your ordering?

**Comment by lxxue** [comment]
Oh I didn't know this before. Thanks for the reference. Mine was just simply like this:
`cell_idx = (x * grid_res_y + y) * grid_res_z + z;`

**Comment by lxxue** [comment]
Looks like this ordering is better than mine (a z squashed in the vertical direction). Do you think if FRNN will be faster with this ordering?

**Comment by yuhao** [comment]
I guess so. I think space-filling curve is generally regarded as the best heuristics for preserving locality.

**Comment by lxxue** [comment]
Thanks, I guess I will try to implement it in the future, but probably not in the near future...

**Comment by yuhao** [comment]
I benchmarked a little bit briefly, and your implementation is generally 2-3 times faster, even though you actually calculate the top K (through MinK) whereas they return immediately whenever they accumulate K neighbors within the radius.

**Comment by lxxue** [comment]
You mean compared with cuNSearch?

**Comment by yuhao** [comment]
yes.

**Comment by lxxue** [comment]
That's good to hear, thanks!
